# Generated by Django 3.1.3 on 2021-11-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hit',
        ),
    ]
