# Generated by Django 3.1.3 on 2021-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_remove_question_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
