# Generated by Django 3.1.3 on 2021-11-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20211102_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
