# Generated by Django 3.1.3 on 2021-11-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_auto_20211102_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
