# Generated by Django 3.1.3 on 2021-11-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20211102_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hit',
        ),
    ]
