# Generated by Django 3.1.3 on 2021-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0018_auto_20211105_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
