# Generated by Django 3.1.3 on 2021-11-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_question_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='view_count',
            new_name='hit',
        ),
        migrations.DeleteModel(
            name='QuestionCount',
        ),
    ]
