# Generated by Django 3.1.3 on 2021-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0021_remove_question_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
