# Generated by Django 3.1.3 on 2021-11-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0022_question_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
    ]
