# Generated by Django 3.1.3 on 2021-11-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0023_auto_20211105_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='hit',
            new_name='view_count',
        ),
    ]
