# Generated by Django 3.1.3 on 2021-11-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0024_auto_20211105_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='view_count',
            new_name='hits',
        ),
    ]
